clearAnnotations()
setMouseMoveSpeed(5.000)
load(filePath="/Users/baaden/ownCloud/fair_covid/ex3_mdtraj/bp151.pdb", readHetm=True, forceDSSP=False, showDefaultRep=True, center=False, modelsAsTraj=True, forceStructureType=-1)
loadTraj("bp151", "/Users/baaden/ownCloud/fair_covid/ex3_mdtraj/bp151.xtc")
enableOutline()
hideSelection("bp151_protein_or_nucleic", "c")
showHideHydrogensInSelection("bp151_not_protein_nucleic")
setHyperBallMetaphore("bp151_not_protein_nucleic", "Licorice", True)
select("resnum 597:900 and protein", "SRBD", True, False, False, True, False, False, True)
select("resnum 0:596 and protein", "ACE", True, False, False, True, False, False, True)
showSelection("SRBD", "c")
colorSelection("SRBD", "c", RGBA(0.031, 0.318, 0.612, 1.000))
showSelection("ACE", "c")
colorSelection("ACE", "c", RGBA(0.992, 0.553, 0.235, 1.000))
select("byres ((around 3.5 ACE) and protein and not ACE)", "ITF1", True, False, False, True, False, False, True)
setUpdateSelectionTraj("ITF1", True)
showSelection("ITF1", "hb")
select("byres ((around 3.5 SRBD) and protein and not SRBD)", "ITF2", True, False, False, True, False, False, True)
setUpdateSelectionTraj("ITF2", True)
showSelection("ITF2", "hb")
updateSelectionWithMDA("ITF1", "around 3.5 ACE", True, False, False)
updateSelectionWithMDA("ITF1", "byres ((around 3.5 ACE) and protein and not ACE)", True, False, False)
setUpdateSelectionTraj("ITF1", False)
setUpdateSelectionTraj("ITF1", True)
updateSelectionWithMDA("ITF1", "byres ((around 3.5 ACE) and protein and not ACE)", True, False, False)
updateSelectionWithMDA("ITF1", "byres ((around 3.5 ACE) and protein and not ACE)", True, False, False)
updateSelectionWithMDA("ITF1", "byres ((around 3.5 ACE) and protein and not ACE) and noh", True, False, False)
updateSelectionWithMDA("ITF1", "byres ((around 3.5 ACE) and protein and not ACE) and not hydrogen", True, False, False)
updateSelectionWithMDA("ITF1", "byres ((around 3.5 ACE) and protein and not ACE) and not H", True, False, False)
setUpdateSelectionTraj("ITF1", False)
setCurrentSelection("ITF1")
showHideHydrogensInSelection("ITF1")
setHyperBallMetaphore("ITF1", "Licorice", True)
setRepSize("ITF1", "hb", 0.70)
setCurrentSelection("ITF2")
updateSelectionWithMDA("ITF2", "byres ((around 3.5 SRBD) and protein and not SRBD)", True, False, False)
showHideHydrogensInSelection("ITF2")
setRepSize("ITF2", "hb", 0.71)
setHyperBallMetaphore("ITF2", "Licorice", True)
setRepSize("ITF2", "hb", 0.70)
bg_color(RGBA(1.000, 1.000, 1.000, 1.000))
enableDepthCueing()
disableDepthCueing()
enableDepthCueing()
setDepthCueingStart(-5.38)
setDepthCueingDensity(0.54)
setDepthCueingStart(-1.48)
setDepthCueingDensity(2.79)
setDepthCueingStart(-1.26)
setOutlineThickness(2.069)
enableDOF()
setDOFFocusDistance(0.580)
setDOFAperture(0.000)
setDOFFocusDistance(0.579)
setDOFAperture(22.064)
setDOFFocalLength(89.504)
setDOFAperture(12.035)
setDepthCueingStart(-0.43)
setDepthCueingDensity(20.00)
setDepthCueingStart(-0.07)
setDepthCueingDensity(-20.00)
setDepthCueingStart(1.66)
setDepthCueingDensity(0.04)
setDepthCueingStart(3.42)
setDepthCueingDensity(3.68)
setDepthCueingStart(-0.93)
setDepthCueingDensity(4.16)
setDOFAperture(38.774)
setDOFFocusDistance(0.507)
setDOFAperture(15.780)
setDOFFocalLength(89.808)
updateSelectionWithMDA("ITF2", "byres ((around 3.5 SRBD) and protein and not SRBD)", True, False, False)
setCurrentSelection("ITF2")
showHideHydrogensInSelection("ITF2")
clearSelections()
setHyperBallMetaphore("ITF2", "Licorice", True)
setRepSize("ITF2", "hb", 0.68)
setDOFFocusDistance(0.489)

setStructurePositionRotation("bp151", Vector3(0.0000, 0.0000, 0.0000), Vector3(0.0000, 0.0000, 0.0000))
#Save parent position
setMolParentTransform( Vector3(-0.0106, 0.0044, -2.4320), Vector3(0.0064, 0.0064, 0.0064), Vector3(339.0814, 240.3680, 328.7000), Vector3(-0.0250, 0.0063, -2.4327) )
